training_class_restricted:
  select_event_style: Training Class
  set_event_title: Generate
  set_event_description: Generate
  select_event_host: Kevin Munro
  click_gotomeeting_checkbox: Click
  set_meeting_url_field: Generate
  set_meeting_phone_field: Generate
  set_meeting_access_code: Generate
  set_date: Generate
  set_start_time: Generate
  set_end_time: Generate
